subinclude("//build_defs:rust")

rust_binary(
    name = "rustc_guessing_game",
    main = "src/main.rs",
    deps = [
        "//third_party/rust:rand",
        "//third_party/rust:rand_core",
    ],
    edition="2021",
)
