plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go-proto",
    revision = "v0.3.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "rust_proto",
    owner = "odonate",
    plugin = "rust-proto",
    revision = "75c233a5d633735a6910f2d1e97295914e013c2c",
)
