plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go-proto",
    revision = "v0.3.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)
