plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go-proto",
    revision = "v0.3.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "rust_proto",
    owner = "odonate",
    plugin = "rust-proto",
    revision = "959cc33a0dfad1fd5241b333cafbfa881f9e35cb",
)
