filegroup(
    name = "rust",
    srcs = [
        "rust_toolchain.build_defs",
        "rust.build_defs",
        "rust_crate.build_defs",
    ],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "fpm",
    srcs = ["fpm.build_defs"],
    visibility = ["PUBLIC"],
)
