sh_binary(
    name = "rustc",
    main = "rustc.sh",
    deps = ["//third_party/rust:toolchain_rustc"],
    visibility=["PUBLIC"],
)

sh_binary(
    name = "cargo",
    main = "cargo.sh",
    deps = ["//third_party/rust:toolchain_cargo"],
    visibility=["PUBLIC"],
)
