sh_binary(
    name = "rustc",
    main = "rustc.sh",
    visibility=["PUBLIC"],
)

sh_binary(
    name = "cargo",
    main = "cargo.sh",
    visibility=["PUBLIC"],
)

sh_binary(
    name = "target",
    main = "target.sh",
    visibility=["PUBLIC"],
)
